pod 'Firebase/Core', '4.0.2'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'chuckit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chuckit

  target 'chuckitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chuckit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chuckit-tvOS

  target 'chuckit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
